[tools]
gh = "latest"
neovim = "0.12.0"
opencode = "latest"
python = "3.11"
uv = "latest"
atuin = "latest"
yazi = "latest"
tmux = "latest"
"aqua:nushell/nushell" = "latest"
ripgrep = "latest"
tree-sitter = "latest"
