[tools]
gh = "latest"
neovim = "0.12.2"
opencode = "latest"
python = "3.12"
uv = "latest"
atuin = "latest"
yazi = "latest"
tmux = "latest"
"aqua:nushell/nushell" = "latest"
ripgrep = "latest"
tree-sitter = "latest"
"aqua:peteretelej/tree" = "latest"
